### ISSUE TITLE
HT

### ISSUE THREAD

**Issue by ptomasroos** [eventchain/eventchain#14]
Hey, dont know if you've seen the projects already but there is some good efforts put into [eventsourced](https://github.com/eligosource/eventsourced) and [eventuate](https://github.com/RBMHTechnology/eventuate) when it comes to eventsourcing and persistance and distribution.

**Comment by yrashk** [comment]
Thanks for sharing! eventsourced looks abandoned and superseded by [Akka Persistence](http://doc.akka.io/docs/akka/snapshot/scala/persistence.html). Eventuate is alive, though.

I'll put [this article](https://krasserm.github.io/2015/05/25/akka-persistence-eventuate-comparison/) here (comparison between these two frameworks).
